development:
  adapter: async
  channel_prefix: instagram_api_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: instagram_api_production
  connection_pool_size: 5
  # Depending on your setup, you might want to adjust the URL and add authentication for Redis
  # If using Heroku, you can set the `REDIS_URL` as an environment variable
  # Example: redis://localhost:6379/1

  # If using AWS or any other cloud service, update the URL accordingly
  # Example: redis://:password@hostname:port/0
